### ISSUE TITLE
Should probably comment out `<base>`

### ISSUE THREAD

**Issue by melyux** [gonejack/webarchive-to-html#1]
Great script, it worked for 99% of things I tried. One thing where it didn't do so hot is when a page has a `<base>` tag. While a Apple's webarchive seems smart enough to ignore this, the HTML output from this script keeps it, so when you open the HTML file, all the local resources try to load starting from whatever's in `<base>`, so everything's broken. Commenting it out fixes things.

**Comment by gonejack** [comment]
Hi, @melyux 

Nice report.
This should be fixed by last commit though without tests, would you like to do a update and check it out by
```
go install github.com/gonejack/webarchive-to-html@main
```

**Comment by melyux** [comment]
Just tried and it works well!
